apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: egress-template
objects:
- kind: Pod
  apiVersion: v1
  metadata:
    name: ${EGRESS_NAME}
    labels:
      name: egress
    annotations:
      pod.network.openshift.io/assign-macvlan: "true"
  spec:
    containers:
    - name: egress-router
      image: openshift3/ose-egress-router
      securityContext:
        privileged: true
      env:
      - name: EGRESS_SOURCE
        value: ${EGRESS_SOURCE}
      - name: EGRESS_GATEWAY
        value: ${EGRESS_GATEWAY}
      - name: EGRESS_DESTINATION
        value: ${EGRESS_DESTINATION}
    serviceAccountName: egress
    nodeSelector:
      tier: ${TIER}
parameters:
- name: EGRESS_NAME
  value: egress-1
  required: true
- name: EGRESS_SOURCE
  value: 192.168.121.200
  required: true
- name: EGRESS_GATEWAY
  value: 192.168.121.1
  required: true
- name: EGRESS_DESTINATION
  value: 192.168.121.92
  required: true
- name: TIER
  value: egress
  required: true
